### ISSUE TITLE
TBTray does nothing?

### ISSUE THREAD

**Issue by mmodler** [sagamusix/TBTray#2]
I'm quite sure its my fault, but i can't bring TBTray to work. Here is what i tried:

Windows 10 x64 1903
Tunderbird 68.2.0 (32-Bit) (C:\Program Files (x86)\Mozilla Thunderbird\thunderbird.exe)

- Uninstalled tb x64, installed 32 bit version
- Registered TBTray
- Reboot, checked taskmanager, TBTray is running
- Start TB, minimize or close => no minimize to tray

I would greatly appreciate get it running, i also tested BirdTray and it was doing to much for me...

Thanks!

**Comment by sagamusix** [comment]
Two ideas:

- Where did you put TBTray.exe? Is it located in the same folder as TB?
- Please verify that TB's main window title ends in "- Mozilla 
Thunderbird". This is what TBTray uses to find the main window and 
become active.

**Comment by mmodler** [comment]
Addition: Microsoft.VS.VC_RuntimeMinimumVSU_x86,v14, installed: {00AC3934-26B4-406E-807C-1692AC7329EC}, version: 14.23.27820

I will check you two ideas, thanks!

**Comment by mmodler** [comment]
Ok, unregistered, placed it in TB folder, re-register, reboot... nothing.

The window name is for example "foo@mymailhost.de - Mozilla Thunderbird"

Last idea: I have two monitors, could this cause the issue?

**Comment by sagamusix** [comment]
It shouldn't be related. Where was the executable located before?
I have a hunch that it could be related to being placed in Program Files 
but I cannot verify that right now.

**Comment by mmodler** [comment]
I copied TBTray from D:\_Downloads\TBTray to C:\Program Files (x86)\Mozilla Thunderbird

The first try with tbtray was from downloads folder and with tb x64 - does this matters?

**Comment by sagamusix** [comment]
It definitely matters that you tried with TB x64 - there is currently no 
x64 version of TBTray. Another tray icon tool I wrote a long time ago 
didn't work when I put it in Program Files at first, that's why I 
thought that maybe this is why TBTray is not working for you. I have not 
tested putting it in Program Files before, so it would make sense to try 
it outside of that again. You don't need to reboot for that, you can 
just kill the previous instance and run the executable directly.

**Comment by mmodler** [comment]
I never had the tool in Program Files - i moved it from downloads to Program Files x86

atm it runs from C:\Program Files (x86)\Mozilla Thunderbird\TBTray.exe

**Comment by mmodler** [comment]
My newer C++ Runtime should be ok?

**Comment by sagamusix** [comment]
I meant both Program Files and Program Files (x86); try placing it 
outside of these UAC-protected folders to see if it makes a difference. 
Also as said try launching it directly instead of relying on autorun. 
The tool runs at a very low priority so it can take a while until it 
actually starts working.

The C++ runtime version doesn't really matter for TBTray.

**Comment by mmodler** [comment]
I started a fresh instance from D:\_Downloads\TBTray - but no functionality closing TB...

**Comment by mmodler** [comment]
Wow if i click TB on the taskbar (not minimize or close IN TB), it works!

**Comment by sagamusix** [comment]
Okay, that sounds like you are experiencing the same issue as this one:
https://github.com/sagamusix/TBTray/issues/1#issuecomment-535878673
This is caused by mail.tabs.drawInTitlebar being set to true.

I have no intention to fix that unless someone provides a patch for it.

**Comment by mmodler** [comment]
With mail.tabs.drawInTitlebar = false it works fine!
